<?php

function online_registration_menu() {
  $items = array();

  $items['registration/form'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Registration Form', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('online_registration_form'), //put the name of the form here
    'access callback' => TRUE
  );

  return $items;
}

function online_registration_form($form, &$form_state) {
  
  $form['data_siswa']['nama_siswa'] = array(
    '#type' => 'textfield',
    '#title' => 'Nama siswa',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );

  $form['data_siswa']['jenis_kelamin'] = array(
    '#type' => 'radios',
    '#title' => 'Jenis kelamin',
    '#options' => array(0 => t('Laki-laki'), 1 => t('Perempuan')),
    '#required' => TRUE,
  );

  $form['data_siswa']['tempat_lahir'] = array(
    '#type' => 'textfield',
    '#title' => 'Tempat lahir',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );

  $form['data_siswa']['tanggal_lahir'] = array(
    '#type' => 'date_popup',
    '#date_timezone' => date_default_timezone(),
    '#date_format' => 'Y-m-d',
    '#date_year_range' => '-30:+3',
    '#title' => 'Tanggal lahir',
    '#required' => TRUE,
  );

  $form['data_siswa']['asal_sekolah'] = array(
    '#type' => 'textfield',
    '#title' => 'Asal sekolah',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );

  $form['data_siswa']['alamat_siswa'] = array(
    '#type' => 'textarea',
    '#title' => 'Alamat siswa',
    '#size' => 255,
    '#maxlength' => 255,
    '#required' => TRUE,
  );

  $form['data_orang_tua']['nama_ayah'] = array(
    '#type' => 'textfield',
    '#title' => 'Nama ayah',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );

  $form['data_orang_tua']['pekerjaan_ayah'] = array(
    '#type' => 'textfield',
    '#title' => 'Pekerjaan ayah',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );

  $form['data_orang_tua']['email_ayah'] = array(
    '#type' => 'textfield',
    '#title' => 'Email ayah',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  
  return $form;
}

function online_registration_form_validate($form, &$form_state) {
  if (!($form_state['values']['price'] > 0)){
    form_set_error('price', t('Price must be a positive number.'));
  }
}

function online_registration_form_submit($form, &$form_state) {
}

/**
 * implements hook_element_info_alter() 
 * 
 */
function hook_element_info_alter(&$type) {
  if (isset($type['date_popup'])) {
    $type['date_popup']['#process'][] = 'online_registration_date_popup_process_alter';
  }
}

/**
 * function to remove the description from date_popup
 * 
 */
 function online_registration_date_popup_process_alter(&$element, &$form_state, $context) {
  unset($element['date']['#description']);
  return $element;
}
